"""change created_at to datetime

Revision ID: 335e97f2a931
Revises: 1990d3bc9ea7
Create Date: 2026-07-22 17:18:15.641094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335e97f2a931'
down_revision: Union[str, Sequence[str], None] = '1990d3bc9ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
ALTER TABLE urls
ALTER COLUMN created_at
TYPE TIMESTAMP WITH TIME ZONE
USING created_at::timestamptz;
""")
    op.execute("""
        ALTER TABLE urls
        ALTER COLUMN expires_at
        TYPE TIMESTAMP WITH TIME ZONE
        USING expires_at::timestamptz;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE urls
        ALTER COLUMN expires_at
        TYPE VARCHAR
        USING expires_at::text;
    """)


    op.execute("""
        ALTER TABLE urls
        ALTER COLUMN created_at
        TYPE VARCHAR
        USING created_at::text;
    """)
    # ### end Alembic commands ###
